//
// DukePersonEntryWeb.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct DukePersonEntryWeb: Codable {


    public var _id: String?

    public var date: BigDecimal

    public var firstname: String

    public var lastname: String

    public var role: String

    public var netid: String

    public var picture: String

    public var email: String

    public var displayDate: String

    public var displayTime: String

    public var backgroundColorCode: String

    public var user: String
    public init(_id: String? = nil, date: BigDecimal, firstname: String, lastname: String, role: String, netid: String, picture: String, email: String, displayDate: String, displayTime: String, backgroundColorCode: String, user: String) { 
        self._id = _id
        self.date = date
        self.firstname = firstname
        self.lastname = lastname
        self.role = role
        self.netid = netid
        self.picture = picture
        self.email = email
        self.displayDate = displayDate
        self.displayTime = displayTime
        self.backgroundColorCode = backgroundColorCode
        self.user = user
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case date
        case firstname
        case lastname
        case role
        case netid
        case picture
        case email
        case displayDate
        case displayTime
        case backgroundColorCode
        case user
    }

}
