//
// Picture.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct Picture: Codable {


    public var _id: String?

    public var netid: String

    public var path: String

    public var size: Int

    public var md5: String
    public init(_id: String? = nil, netid: String, path: String, size: Int, md5: String) { 
        self._id = _id
        self.netid = netid
        self.path = path
        self.size = size
        self.md5 = md5
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case netid
        case path
        case size
        case md5
    }

}
