//
// PictureJSON.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct PictureJSON: Codable {


    public var netid: String

    public var fileEntity: String

    public var fileExtension: String
    public init(netid: String, fileEntity: String, fileExtension: String) { 
        self.netid = netid
        self.fileEntity = fileEntity
        self.fileExtension = fileExtension
    }
    public enum CodingKeys: String, CodingKey { 
        case netid
        case fileEntity = "file_entity"
        case fileExtension = "file_extension"
    }

}
